### ISSUE TITLE
Improve documentation - Add text describing each function / variables

### ISSUE THREAD

**Issue by jcfr** [commontk/Artichoke#10]

**Comment by rleigh-dundee** [comment]
Hi,

I was just about to report this very issue.  I've been trying to set up a superbuild with Artichoke using other projects as examples, but so much of it is completely opaque.  It looks incredibly useful and there's clearly a lot of thought and effort gone into it, but without documentation it's incredibly difficult for a newcomer to grasp how to use it correctly.

- It's not clear what a lot of the macros do (e.g. what does `mark_as_superbuild` do, why would I need to use it, and what are its side effects?)
- It's not clear what most of the macro parameters do (what is their purpose and effect, do they need to be set before calling, are they modified after calling, etc.  For example, what is the purpose and behaviour of `SUPERBUILD_VAR`; it clearly has an effect in setting EP_ARGS_VAR which is otherwise left unset, but when and why would I want to do this, and what are the benefits of doing so, etc.)

And for certain tasks it looks like it *might* be possible, but not clear how to do it.  For example, passing `CMAKE_PREFIX_PATH` in CMAKE_ARGS/CMAKE_CACHE_ARGS; I need to escape the ';' separators and there's logic to do this, but how do I instruct it to be passed.  I can do it by hand, but it looks like `_sb_get_external_project_arguments` *might* be able to do this if only I knew how to set things up correctly.

Regards,
Roger

**Comment by jcfr** [comment]
Hi Roger, 

Thanks for the feedback. I couldn't agree more.

If you would like we could have a short google hangout where I would (1) walk you through all functions and (2) illustrate how they are used (for example in Slicer and CTK build system). 

When done, if you feel comfortable you could then submit a pull request to clarify and improve the existing documentation.

Here is a link that could help clarify some of your questions:  http://www.cmake.org/pipermail/cmake/2014-June/057738.html

> what does mark_as_superbuild do, why would I need to use it, and what are its side effects?

This is used to pass variable to one or more external projects. It basically avoid you to explicitly add option to `CMAKE_ARGS` or `CMAKE_CACHE_ARGS`

Let me know what you think, 

Best, 
J-Christophe

**Comment by rleigh-dundee** [comment]
Thanks for the offer, but I'm currently still investigating the options for what to use so I can't commit to spend time working on something my organisation might not use.  If this turns out to be the best option, then I would be happy to have a chat about it.


Thanks,
Roger

**Comment by jcfr** [comment]
Closing. Documentation is now generated using readthedocs.
